credentials:
  usernames:
    demo_user:
      email: demo@example.com
      name: Demo User
      password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
  cookie:
    expiry_days: 30
    key: some_signature_key
    name: fuzzy_image_auth
