credentials:
  usernames:
    demo_user:
      name: Demo User
      email: demo@example.com
      password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
  cookie:
    expiry_days: 30
    key: fuzzy_key
    name: fuzzy_cookie
