services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "streamlit run streamlit_app.py --server.port=${PORT:-8501} --server.address=0.0.0.0"
    systemPackages:
      - libgl1
      - libglib2.0-0
